%YAML:1.0
camera_name: "raspicam"
image_width: 410
image_height: 308
camera_matrix:
   rows: 3
   cols: 3
   dt: d
   data: [350.0,  0.0, 205.0,
          0.0, 350.0, 154.0,
          0.0,  0.0,  1.0]
distortion_model: "plumb_bob"
distortion_coefficients:
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0,
          0.0, 1.0, 0.0,
          0.0, 0.0, 1.0]
projection_matrix:
   rows: 3
   cols: 4
   dt: d
   data: [350.0,  0.0, 205.0, 0.0,
          0.0, 350.0, 154.0, 0.0,
          0.0,  0.0,  1.0, 0.0]
