%YAML:1.0

# Common parameters
imu: 1         
num_of_cam: 1  

imu_topic: "/imu_plugin/out"
image0_topic: "/raspberrypi_camera/image_raw"
output_path: "~/output/"

cam0_calib: "raspicam.yaml"
image_width: 410
image_height: 308

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0  
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
           0.999557249008, 0.0149672133247, 0.025715529948,  -0.064676986768,
           -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
           0, 0, 0, 1]

# Multiple thread support
multiple_thread: 1

# Feature tracker parameters
max_cnt: 150
min_dist: 50
freq: 10
F_threshold: 1.0
show_track: 1
flow_back: 1

# Optimization parameters
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0

# IMU parameters
acc_n: 0.1
gyr_n: 0.01
acc_w: 0.001
gyr_w: 0.0001
g_norm: 9.81007

# Unsynchronization parameters
estimate_td: 0
td: 0.0

# Loop closure parameters
load_previous_pose_graph: 0
pose_graph_save_path: "~/output/pose_graph/"
save_image: 1
